import 'focus-visible';
import 'wicg-inert';
import 'fslightbox';
import { changeMenuHeight } from './modules/vh';
import { scrollHeader, toggleMenu, toggleSearch } from './modules/header';
import { createPhoneMask } from './modules/inputmask';
import { createSwiper } from './modules/swiper';
import { createMap } from './modules/map';
import { changeFilter } from './modules/filters';
import { changeCatalog } from './modules/catalog';
import { initScroll } from './modules/scroll';
import { toggleProduct } from './modules/product';
import { openForm } from './modules/modal';
import { sendForm } from './modules/send';
import { openPortfolioBalloon } from './modules/portfolio';
import { createConstructor } from './modules/constructor';
import { openItemServiceMore } from './modules/service';

changeMenuHeight();
scrollHeader();
toggleMenu();
toggleSearch();
createPhoneMask();
createSwiper();
createMap();
changeFilter();
changeCatalog();
initScroll();
toggleProduct();
openForm();
sendForm();
openPortfolioBalloon();
createConstructor();
openItemServiceMore();
